name: myenv
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.13.2
  - aiosignal==1.4.0
  - annotated-types==0.7.0
  - anyio==4.11.0
  - asttokens==3.0.0
  - asyncio==4.0.0
  - attrs==25.4.0
  - beautifulsoup4==4.14.2
  - blis==1.3.0
  - catalogue==2.0.10
  - certifi==2025.10.5
  - charset-normalizer==3.4.4
  - click==8.3.0
  - cloudpathlib==0.23.0
  - comm==0.2.3
  - confection==0.1.5
  - contourpy==1.3.3
  - coreference-eval==0.0.2
  - cycler==0.12.1
  - cymem==2.0.11
  - datasets==4.4.1
  - debugpy==1.8.17
  - decorator==5.2.1
  - dill==0.4.0
  - en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
  - executing==2.2.1
  - fastcoref==2.1.6
  - filelock==3.20.0
  - fire==0.7.1
  - fonttools==4.60.1
  - frame-semantic-transformer==0.10.0
  - frozenlist==1.8.0
  - fsspec==2025.10.0
  - gdown==5.2.0
  - greenlet==3.2.4
  - grpcio==1.76.0
  - h11==0.16.0
  - hf-xet==1.2.0
  - httpcore==1.0.9
  - httpx==0.28.1
  - huggingface-hub==0.36.0
  - idna==3.11
  - ipykernel==7.1.0
  - ipython==9.7.0
  - ipython_pygments_lexers==1.1.1
  - isanlp @ git+https://github.com/iinemo/isanlp.git@8b8dbb998171e2fd1430a47f21902f9ad094e553
  - isanlp_rst==3.2.0
  - jedi==0.19.2
  - Jinja2==3.1.6
  - joblib==1.5.2
  - jsonnet==0.21.0
  - jupyter_client==8.6.3
  - jupyter_core==5.9.1
  - kiwisolver==1.4.9
  - lightning-utilities==0.15.2
  - lxml==6.0.2
  - MarkupSafe==3.0.3
  - matplotlib==3.10.7
  - matplotlib-inline==0.2.1
  - mpmath==1.3.0
  - multidict==6.7.0
  - multiprocess==0.70.18
  - murmurhash==1.0.13
  - nest-asyncio==1.6.0
  - networkx==3.5
  - nlpaug==1.1.11
  - nltk==3.9.2
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.8.4.1
  - nvidia-cuda-cupti-cu12==12.8.90
  - nvidia-cuda-nvrtc-cu12==12.8.93
  - nvidia-cuda-runtime-cu12==12.8.90
  - nvidia-cudnn-cu12==9.10.2.21
  - nvidia-cufft-cu12==11.3.3.83
  - nvidia-cufile-cu12==1.13.1.3
  - nvidia-curand-cu12==10.3.9.90
  - nvidia-cusolver-cu12==11.7.3.90
  - nvidia-cusparse-cu12==12.5.8.93
  - nvidia-cusparselt-cu12==0.7.1
  - nvidia-nccl-cu12==2.27.5
  - nvidia-nvjitlink-cu12==12.8.93
  - nvidia-nvshmem-cu12==3.3.20
  - nvidia-nvtx-cu12==12.8.90
  - packaging==25.0
  - pandas==2.3.3
  - parso==0.8.5
  - pexpect==4.9.0
  - pillow==12.0.0
  - platformdirs==4.5.0
  - playwright==1.55.0
  - preshed==3.0.10
  - prompt_toolkit==3.0.52
  - propcache==0.4.1
  - protobuf==3.18.3
  - psutil==7.1.3
  - ptyprocess==0.7.0
  - pure_eval==0.2.3
  - pyarrow==22.0.0
  - pydantic==2.12.4
  - pydantic_core==2.41.5
  - pyee==13.0.0
  - Pygments==2.19.2
  - pyparsing==3.2.5
  - PySocks==1.7.1
  - python-dateutil==2.9.0.post0
  - pytorch-lightning==1.9.5
  - pytz==2025.2
  - PyYAML==6.0.3
  - pyzmq==27.1.0
  - razdel==0.5.0
  - regex==2025.11.3
  - requests==2.32.5
  - safetensors==0.6.2
  - scipy==1.16.3
  - sentencepiece==0.1.99
  - setuptools==80.9.0
  - six==1.17.0
  - smart_open==7.5.0
  - sniffio==1.3.1
  - soupsieve==2.8
  - spacy==3.8.8
  - spacy-legacy==3.0.12
  - spacy-loggers==1.0.5
  - srsly==2.5.1
  - stack-data==0.6.3
  - sympy==1.14.0
  - termcolor==3.2.0
  - thinc==8.3.8
  - tiktoken==0.12.0
  - tokenizers==0.20.3
  - torch==2.9.0
  - torchmetrics==1.8.2
  - tornado==6.5.2
  - tqdm==4.67.1
  - traitlets==5.14.3
  - transformers==4.46.0
  - triton==3.5.0
  - typer-slim==0.20.0
  - typing-inspection==0.4.2
  - typing_extensions==4.15.0
  - tzdata==2025.2
  - urllib3==2.5.0
  - wasabi==1.1.3
  - wcwidth==0.2.14
  - weasel==0.4.2
  - wrapt==2.0.1
  - xxhash==3.6.0
  - yarl==1.22.0
